/** navigationSchema/admin.js — Admin portal navigation. */

import {
  LayoutDashboard,
  Users,
  Building2,
  Package,
  Settings,
  FileText,
  ScrollText,
  CreditCard,
  Calculator,
  FileCheck,
  Calendar,
  Banknote,
  Receipt,
  TrendingUp,
  Wallet,
  UserCog,
  DollarSign,
  Gift,
  ClipboardList,
  ShoppingCart,
  Truck,
  Store,
  BarChart3,
  Boxes,
  ArrowLeftRight,
  ClipboardCheck,
  WrenchIcon,
  Crown,
  Sparkles,
  Brain,
  MessageSquare,
  Shield,
  Activity,
  Star,
  AlertTriangle,
  Layers,
  BookOpen,
  Archive,
  Target,
  Workflow,
  Coffee,
  ListChecks,
  History,
  BellRing,
  ChevronRight,
  Landmark,
  LineChart,
  PiggyBank,
  QrCode,
  FileSpreadsheet,
  CalendarCheck,
} from "lucide-react";

// eslint-disable-next-line no-unused-vars
export const adminNav = {
  id: "admin",
  name: "Admin Portal",
  sections: [
    {
      id: "dashboard",
      name: "Dashboard",
      icon: LayoutDashboard,
      items: [
        { id: "overview", name: "Overview", path: "/admin" },
      ],
    },
    {
      id: "user-management",
      name: "User Management",
      icon: Users,
      reqPerm: "admin.user",
      items: [
        { id: "users", name: "All Users", path: "/admin/users" },
        { id: "roles", name: "Roles & Permissions", path: "/admin/roles" },
        { id: "audit-log", name: "Activity Log", path: "/admin/audit-log" },
      ],
    },
    {
      id: "master-data",
      name: "Master Data",
      icon: Package,
      reqPerm: "admin.master_data",
      items: [
        { id: "master-data-hub", name: "Items • Vendors • Outlets • Brands • Employees", path: "/admin/master-data" },
      ],
    },
    {
      id: "configuration",
      name: "Configuration",
      icon: Shield,
      reqPerm: "admin.business_rules",
      items: [
        { id: "business-rules", name: "Business Rules", path: "/admin/configuration" },
        { id: "approval-matrix", name: "Approval Matrix", path: "/admin/approvals", badge: "Builder" },
        // REMOVED: Approval Workflows (Legacy) - superseded by Approval Matrix Builder
        { id: "bulk-import", name: "Bulk Excel Import", path: "/admin/bulk-import", badge: "New" },
        { id: "number-series", name: "Number Series", path: "/admin/number-series" },
        { id: "integrations", name: "Integrations", path: "/admin/integrations" },
        { id: "tax-config", name: "Tax Config", path: "/admin/tax" },
      ],
    },
    {
      id: "loyalty-admin",
      name: "Loyalty Program",
      icon: Star,
      items: [
        { id: "loyalty-overview", name: "Loyalty Overview", path: "/admin/loyalty" },
        { id: "loyalty-customers", name: "Customers", path: "/admin/loyalty/customers" },
        { id: "loyalty-rewards", name: "Rewards Catalog", path: "/admin/loyalty/rewards" },
        { id: "loyalty-redemptions", name: "Redemptions", path: "/admin/loyalty/redemptions" },
        { id: "loyalty-analytics", name: "CRM Analytics", path: "/admin/loyalty/analytics" },
      ],
    },
    {
      id: "operations-monitoring",
      name: "Operations & Monitoring",
      icon: Activity,
      reqPerm: "admin.audit_log",
      items: [
        { id: "ops-metrics", name: "System Metrics", path: "/admin/operations" },
        { id: "ops-logs", name: "System Logs", path: "/admin/operations/logs" },
        { id: "ops-scheduler", name: "Scheduler", path: "/admin/operations/scheduler" },
        { id: "ops-archival", name: "Archival", path: "/admin/operations/archival" },
        { id: "ops-rate-limits", name: "Rate Limits", path: "/admin/operations/rate-limits" },
        { id: "report-schedules", name: "Laporan Terjadwal", path: "/admin/report-schedules" },
        { id: "data-management", name: "Manajemen Data", path: "/admin/data-management" },
        { id: "tour-analytics", name: "Tour Analytics", path: "/admin/tour-analytics" },
      ],
    },
    {
      id: "settings",
      name: "System Settings",
      icon: Settings,
      reqPerm: "admin.system_settings",
      items: [
        { id: "general", name: "General", path: "/admin/settings" },
      ],
    },
    {
      id: "cms",
      name: "CMS Studio",
      icon: FileText,
      reqPerm: "admin.cms",
      items: [
        { id: "cms-studio", name: "Brands • News • Menu • Pages • Media", path: "/admin/cms/brands" },
      ],
    },
    {
      id: "seo",
      name: "Smart SEO",
      icon: Sparkles,
      reqPerm: "admin.cms",
      items: [
        { id: "smart-seo", name: "Smart SEO AI", path: "/admin/smart-seo", badge: "AI" },
      ],
    },
  ],
};
